#!/usr/bin/env python3
"""KiCad projects for the boards, from the circuits the .circ files come from.

    python3 logisim/python/build_kicad.py [board ...]
    python3 logisim/python/build_kicad.py --route [board ...]

One directory per board under logisim/kicad/, each a KiCad project with its own
symbol and footprint library: KiCad's own libraries are a separate install and
this way the boards do not depend on which version of them is present.

--route reads the .ses Freerouting wrote for a board and regenerates its .kicad_pcb
with those tracks in it.
"""

import sys
from pathlib import Path

from logisim.kicad import BACKPLANE, Board, parse_ses, write
from build_regfile import regfile

OUT = Path(__file__).resolve().parents[1] / "kicad"

# name -> (the circuit it is made of, chips per row on the board)
BOARDS = {"regfile": (regfile, 8)}


MEANING = {
    "+5V": "supply", "GND": "ground",
    "BI": "bus into the register file (the CPU's write bus)",
    "BO": "bus out of the register file (the CPU's read bus)",
    "A": "register address", "RD": "read strobe", "WR": "write strobe",
    "CLK": "system clock", "SP": "spare",
}


def pinout(path, boards):
    """The backplane table, the same on every board."""
    used = {}
    for name, board in boards.items():
        for net in {n for _, n in board.backplane if n}:
            used.setdefault(net, []).append(name)
    rows = ["# Backplane pinout", "",
            "Generated by `build_kicad.py`; every board carries this 2x20 header,",
            "wired where the board has that signal.", "",
            "| Pin | Signal | Meaning | Boards |", "| --- | --- | --- | --- |"]
    for i, net in enumerate(BACKPLANE):
        key = net.rstrip("0123456789") or net
        rows.append(f"| {i + 1} | `{net}` | {MEANING.get(key, '')} | "
                    f"{', '.join(used.get(net, [])) or '-'} |")
    path.write_text("\n".join(rows) + "\n")
    return path


if __name__ == "__main__":
    args = sys.argv[1:]
    route = "--route" in args
    wanted, built = [a for a in args if a != "--route"] or list(BOARDS), {}
    for name in wanted:
        if name not in BOARDS:
            sys.exit(f"no board {name!r}; have {', '.join(BOARDS)}")
        build, columns = BOARDS[name]
        board = Board(name, build(), columns=columns)
        tracks, vias = (), ()
        if route:
            session = OUT / name / f"{name}.ses"
            if not session.exists():
                sys.exit(f"no {session}; run the router first")
            tracks, vias = parse_ses(session.read_text(), board)
        print(write(board, OUT / name, tracks, vias),
              f"({len(board.parts)} parts, {len(board.nets())} nets"
              + (f", {sum(len(p) - 1 for *_, p in tracks)} segments, "
                 f"{len(vias)} vias)" if route else ")"))
        built[name] = board
    print(pinout(OUT / "BACKPLANE.md", built))
