#!/usr/bin/env python3
"""KiCad projects for the boards, from the circuits the .circ files come from.

    python3 logisim/python/build_kicad.py [board ...]
    python3 logisim/python/build_kicad.py --route [board ...]

One directory per board under logisim/kicad/, each a KiCad project with its own
symbol and footprint library: KiCad's own libraries are a separate install and
this way the boards do not depend on which version of them is present.

--route insists on the .ses Freerouting wrote for a board; without it, a session
lying next to the board is used anyway, so regenerating keeps the routing.
"""

import sys
from pathlib import Path

from logisim.kicad import (
    Board,
    HEADER_PINS,
    backplane,
    parse_ses,
    system_nets,
    write,
)
from build_alu import alu
from build_kone import datapath, io, kone, memory, sequencer
from build_regfile import regfile
from kone_microcode import assemble

OUT = Path(__file__).resolve().parents[1] / "kicad"

# name -> chips per row on the board
BOARDS = {
    "regfile": 8,
    "alu": 6,
    "datapath": 6,
    "sequencer": 4,
    "memory": 3,
    "io": 6,
}

# The board the whole stack is fed through.
ENTRY = "io"


def blocks():
    """The six circuits of the CPU, in the order kone() takes them."""
    rom, dispatch_a, dispatch_b, _, _ = assemble()
    return {
        "regfile": regfile(),
        "alu": alu(),
        "sequencer": sequencer(rom, dispatch_a, dispatch_b),
        "datapath": datapath(),
        "memory": memory(b""),
        "io": io(),
    }


# What to actually order: the generic 74xx name a circuit uses, the part it
# becomes, and what it does. HC throughout, which is what the current draw in
# BACKPLANE.md assumes; LS works as well but takes about five times the supply.
CHIPS = {
    "7404": ("74HC04", "hex inverter"),
    "7408": ("74HC08", "quad 2-input AND"),
    "7411": ("74HC11", "triple 3-input AND"),
    "7421": ("74HC21", "dual 4-input AND"),
    "7427": ("74HC27", "triple 3-input NOR"),
    "7432": ("74HC32", "quad 2-input OR"),
    "7486": ("74HC86", "quad 2-input XOR"),
    "74138": ("74HC138", "3-to-8 decoder"),
    "74151": ("74HC151", "8:1 multiplexer"),
    "74153": ("74HC153", "dual 4:1 multiplexer"),
    "74157": ("74HC157", "quad 2:1 multiplexer"),
    "74245": ("74HC245", "octal bus transceiver"),
    "74283": ("74HC283", "4-bit binary adder"),
    "74377": ("74HC377", "octal register, clock enable"),
    "28C256": ("AT28C256-15PU", "32K x 8 EEPROM, parallel"),
    "62256": ("AS6C62256-55PCN", "32K x 8 SRAM"),
}

# Everything a board needs that is not a chip.
PASSIVES = {
    "100n": ("ceramic 100nF, 5.08mm", "one per IC, decoupling"),
    "100u": ("electrolytic 100uF/16V, 2.5mm", "bulk, one per board"),
    "220R": ("resistor 220R, 1/4W", "power LED series resistor"),
    "PWR": ("LED 3mm", "power indicator"),
    "5V IN": ("screw terminal 2x5.08mm", "supply entry"),
    "Power": ("pin header 1x02", "supply header"),
    "M3": ("M3 hole, screw and standoff", "stacking"),
}


def bom(path, boards):
    """Every part the six boards need, counted per board."""
    names = list(boards)
    count = {}
    for name, board in boards.items():
        for part in board.parts:
            if part.symbol == "PWR":
                continue
            value = part.value if not part.value.startswith("Backplane") \
                else "Backplane"
            count.setdefault(value, dict.fromkeys(names, 0))[name] += 1

    def table(rows, kind):
        out = [f"| {kind} | Package | Function | "
               + " | ".join(names) + " | Total |",
               "| --- | --- | --- | " + " | ".join("---" for _ in names)
               + " | --- |"]
        for value, part, what, package in rows:
            per = count[value]
            out.append(
                f"| `{part}` | {package} | {what} | "
                + " | ".join(str(per[n] or "") for n in names)
                + f" | **{sum(per.values())}** |"
            )
        return out

    chips = [
        (v, CHIPS[v][0], CHIPS[v][1],
         next(iter(p.footprint for b in boards.values() for p in b.parts
                   if p.value == v)).split("_")[0])
        for v in sorted(count, key=lambda v: (-sum(count[v].values()), v))
        if v in CHIPS
    ]
    rest = [
        (v, PASSIVES[v][0], PASSIVES[v][1], "-")
        for v in sorted(count) if v in PASSIVES
    ] + [("Backplane", "pin header 2x20, stackable", "board to board",
          "2.54mm")]

    rows = [
        "# Parts list",
        "",
        "Generated by `build_kicad.py` from the boards themselves, so it counts",
        "what is actually placed. Every logic part is a DIP; 74HC throughout,",
        "which is what the supply estimate in `BACKPLANE.md` assumes.",
        "",
        "## Logic and memory",
        "",
        *table(chips, "Part"),
        "",
        f"{sum(sum(count[v].values()) for v, *_ in chips)} chips in total. "
        "Sockets are worth it for the two memory types, which are the",
        "parts you will want to reprogram. `74HC21` and `74HC27` are the two",
        "that are thinly stocked; the LS or HCT versions drop in.",
        "",
        "## Everything else",
        "",
        *table(rest, "Part"),
    ]
    path.write_text("\n".join(rows) + "\n")
    return path


def pinout(path, signals, boards):
    """The backplane table and how the stack is powered, both generated."""
    rows = [
        "# Backplane pinout",
        "",
        "Generated by `build_kicad.py` from the top level of `kone.circ`, so a",
        f"pin means the same thing on every board. {HEADER_PINS} pins per 2x20",
        "connector; a board carries the connectors it has signals on, all at",
        "the same place on the board so a stack lines up.",
        "",
        "| Connector | Pin | Signal | Boards |",
        "| --- | --- | --- | --- |",
    ]
    for i, signal in enumerate(signals):
        on = [name for name, board in boards.items() if i in board.used]
        rows.append(
            f"| BP{i // HEADER_PINS + 1} | {i % HEADER_PINS + 1} | "
            f"`{signal}` | {', '.join(on) or '-'} |"
        )

    ics = {
        name: sum(1 for p in board.parts if p.ref.startswith("U"))
        for name, board in boards.items()
    }
    rows += [
        "",
        "## Power",
        "",
        f"The stack has one supply entry, on the `{ENTRY}` board: a 2-pin screw",
        "terminal (J5) feeding `+5V` and `GND` into the backplane. Every other",
        "board is powered through the backplane connectors alone -- there is no",
        "regulator anywhere on the stack, so the supply has to be regulated 5 V.",
        "`io` also carries the power indicator, an LED with a 220 ohm resistor",
        "(about 14 mA). Each board has a 100 uF bulk capacitor beside its",
        "connectors, and every IC its own 100 nF.",
        "",
        "| Board | ICs |",
        "| --- | --- |",
    ]
    for name, count in sorted(ics.items(), key=lambda kv: (-kv[1], kv[0])):
        rows.append(f"| {name} | {count} |")
    rows += [
        f"| **total** | **{sum(ics.values())}** |",
        "",
        f"Supply: **5 V regulated**. {sum(ics.values())} packages, ten of them",
        "28-pin memories. With 74HC parts at a few mA each and 10-30 mA per",
        "memory, the stack draws roughly 0.5 to 1 A at a low clock, so a 5 V /",
        "2 A supply leaves headroom. 74LS parts instead would multiply that by",
        "about five, which is worth checking before choosing a supply.",
    ]
    path.write_text("\n".join(rows) + "\n")
    return path


if __name__ == "__main__":
    args = sys.argv[1:]
    route = "--route" in args
    wanted, built = [a for a in args if a != "--route"] or list(BOARDS), {}
    circuits = blocks()
    system = system_nets(kone(tuple(circuits.values())))
    signals = backplane(system)
    positions = {signal: i for i, signal in enumerate(signals)}

    def make(name, size=None):
        return Board(
            name,
            circuits[name],
            columns=BOARDS[name],
            ports={
                port: net
                for (block, port), net in system.items()
                if block == name
            },
            positions=positions,
            size=size,
            entry=name == ENTRY,
        )

    # Every board gets the outline the largest one needs, so a stack of them
    # lines up on its standoffs.
    measured = [make(name) for name in BOARDS]
    size = (
        max(b.width for b in measured),
        max(b.height for b in measured),
    )
    for name in wanted:
        if name not in BOARDS:
            sys.exit(f"no board {name!r}; have {', '.join(BOARDS)}")
        board = make(name, size)
        tracks, vias = (), ()
        # A session from an earlier run is kept, so regenerating a board does
        # not silently throw its routing away.
        session = OUT / name / f"{name}.ses"
        if route and not session.exists():
            sys.exit(f"no {session}; run the router first")
        if session.exists():
            tracks, vias = parse_ses(session.read_text(), board)
        print(
            write(board, OUT / name, tracks, vias),
            f"({len(board.parts)} parts, {len(board.nets())} nets"
            + (
                f", {sum(len(p) - 1 for *_, p in tracks)} segments, "
                f"{len(vias)} vias)"
                if tracks
                else ")"
            ),
        )
        built[name] = board
    print(pinout(OUT / "BACKPLANE.md", signals, built))
    # The parts list is documentation, not a build artifact, so it lives
    # beside the README rather than in the ignored kicad/ tree.
    print(bom(OUT.parent / "PARTS.md", built))
