#!/usr/bin/env python3
"""KiCad projects for the boards, from the circuits the .circ files come from.

    python3 logisim/python/build_kicad.py [board ...]
    python3 logisim/python/build_kicad.py --route [board ...]

One directory per board under logisim/kicad/, each a KiCad project with its own
symbol and footprint library: KiCad's own libraries are a separate install and
this way the boards do not depend on which version of them is present.

--route insists on the .ses Freerouting wrote for a board; without it, a session
lying next to the board is used anyway, so regenerating keeps the routing.
"""

import sys
from pathlib import Path

from logisim.kicad import (
    Board,
    HEADER_PINS,
    backplane,
    parse_ses,
    system_nets,
    write,
)
from build_alu import alu
from build_kone import datapath, io, kone, memory, sequencer
from build_regfile import regfile
from kone_microcode import assemble

OUT = Path(__file__).resolve().parents[1] / "kicad"

# name -> chips per row on the board
BOARDS = {
    "regfile": 8,
    "alu": 6,
    "datapath": 6,
    "sequencer": 4,
    "memory": 3,
    "io": 6,
}


def blocks():
    """The six circuits of the CPU, in the order kone() takes them."""
    rom, dispatch_a, dispatch_b, _, _ = assemble()
    return {
        "regfile": regfile(),
        "alu": alu(),
        "sequencer": sequencer(rom, dispatch_a, dispatch_b),
        "datapath": datapath(),
        "memory": memory(b""),
        "io": io(),
    }


def pinout(path, signals, boards):
    """The backplane table: the same signal sits on the same pin everywhere."""
    rows = [
        "# Backplane pinout",
        "",
        "Generated by `build_kicad.py` from the top level of `kone.circ`, so a",
        f"pin means the same thing on every board. {HEADER_PINS} pins per 2x20",
        "connector; a board carries the connectors it has signals on.",
        "",
        "| Connector | Pin | Signal | Boards |",
        "| --- | --- | --- | --- |",
    ]
    for i, signal in enumerate(signals):
        on = [name for name, board in boards.items() if i in board.used]
        rows.append(
            f"| BP{i // HEADER_PINS + 1} | {i % HEADER_PINS + 1} | "
            f"`{signal}` | {', '.join(on) or '-'} |"
        )
    path.write_text("\n".join(rows) + "\n")
    return path


if __name__ == "__main__":
    args = sys.argv[1:]
    route = "--route" in args
    wanted, built = [a for a in args if a != "--route"] or list(BOARDS), {}
    circuits = blocks()
    system = system_nets(kone(tuple(circuits.values())))
    signals = backplane(system)
    positions = {signal: i for i, signal in enumerate(signals)}
    for name in wanted:
        if name not in BOARDS:
            sys.exit(f"no board {name!r}; have {', '.join(BOARDS)}")
        board = Board(
            name,
            circuits[name],
            columns=BOARDS[name],
            ports={
                port: net
                for (block, port), net in system.items()
                if block == name
            },
            positions=positions,
        )
        tracks, vias = (), ()
        # A session from an earlier run is kept, so regenerating a board does
        # not silently throw its routing away.
        session = OUT / name / f"{name}.ses"
        if route and not session.exists():
            sys.exit(f"no {session}; run the router first")
        if session.exists():
            tracks, vias = parse_ses(session.read_text(), board)
        print(
            write(board, OUT / name, tracks, vias),
            f"({len(board.parts)} parts, {len(board.nets())} nets"
            + (
                f", {sum(len(p) - 1 for *_, p in tracks)} segments, "
                f"{len(vias)} vias)"
                if tracks
                else ")"
            ),
        )
        built[name] = board
    print(pinout(OUT / "BACKPLANE.md", signals, built))
